# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Upload env"
  build:
    name: Upload env
    runs-on: ubuntu-latest
    steps:
    - name: Repository checkout
      uses: actions/checkout@v2
    - name: Connects to VPS via SSH
      uses: garygrossgarten/github-action-ssh@release
      env:
        FOO: "HERE"
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        privateKey: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        command: |
          echo "I am $FOO"
