# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Upload env"
  build:
    name: Upload env
    runs-on: ubuntu-18.04
    steps:
    - name: Set up QEMU
    - uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
    - uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
    - uses: docker/build-push-action@v3
      with:
        push: true
        tags: jakubblockczech/react-app-frontend:latest

    - name: Deploy on Digital Ocean
    - uses: actions/checkout@v3
      env:
        PRIVATE_KEY: ${{ secrets.SSH_KEY  }}
        HOSTNAME : ${{ secrets.SSH_HOST  }}
        USER_NAME : ${{ secrets.SSH_USERNAME  }}
            
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ls
        ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          echo starting instance action
          '
